# Generated by Django 4.2.7 on 2025-07-20 05:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nama Kategori')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategori',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Produk')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(verbose_name='Deskripsi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Harga')),
                ('image', models.ImageField(upload_to='products/%Y/%m/%d/', verbose_name='Gambar Produk')),
                ('affiliate_link', models.URLField(verbose_name='Link Afiliasi')),
                ('meta_title', models.CharField(blank=True, max_length=100)),
                ('meta_description', models.CharField(blank=True, max_length=200)),
                ('is_featured', models.BooleanField(default=False, verbose_name='Produk Unggulan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='affiliate_app.category', verbose_name='Kategori')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Produk',
                'verbose_name_plural': 'Produk',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='affiliate_a_slug_73b522_idx'), models.Index(fields=['name'], name='affiliate_a_name_a0b9fc_idx'), models.Index(fields=['category'], name='affiliate_a_categor_dd5a8b_idx'), models.Index(fields=['is_active'], name='affiliate_a_is_acti_526042_idx'), models.Index(fields=['is_featured'], name='affiliate_a_is_feat_bc7956_idx')],
            },
        ),
    ]
