# Generated by Django 4.2.7 on 2025-07-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nama Kategori'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
