# Generated by Django 4.2.7 on 2025-07-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate_app', '0002_alter_category_name_alter_product_meta_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
